### ISSUE TITLE
Error world is null

### ISSUE THREAD

**Issue by sanderdatema** [bigstickpolicies/troddenpath#1]
I love the plugin, at least the idea, cause I can't get it to run. 😀 

This is the error I get every second (repeating):
```
[11:22:37 WARN]: [TroddenPath] Task #78 for TroddenPath v1.0.0 generated an exception
java.lang.NullPointerException: Cannot invoke "org.bukkit.World.getEntitiesByClasses(java.lang.Class[])" because "world" is null
        at com.bigstickpolicies.troddenpath.tread.PathTreader.lambda$new$1(PathTreader.java:34) ~[troddenpath-v1.6.jar:?]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[patched_1.17.1.jar:git-Purpur-1393]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[patched_1.17.1.jar:git-Purpur-1393]
        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1574) ~[patched_1.17.1.jar:git-Purpur-1393]
        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:493) ~[patched_1.17.1.jar:git-Purpur-1393]
        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1490) ~[patched_1.17.1.jar:git-Purpur-1393]
        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1283) ~[patched_1.17.1.jar:git-Purpur-1393]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:321) ~[patched_1.17.1.jar:git-Purpur-1393]
        at java.lang.Thread.run(Thread.java:831) [?:?]
```

There are more worlds on my server, but it seems the plugin can't get beyond the first (and default) one. I even disabled it in the config, but that wouldn't help.

**Comment by bigstickpolicies** [comment]
Did you try changing the worlds option in the config?

worlds: ["world","world_nether","world_the_end"]

Try removing "world","world_nether", "world_the_end", and adding all the worlds you want TroddenPath to be enabled in.

**Comment by sanderdatema** [comment]
> I even disabled it in the config, but that wouldn't help.
Yep, I tried that. ;)

**Comment by bigstickpolicies** [comment]
Hmmm... I managed to reproduce the error (by changing the world name), but it resolved for me when I changed the config. Does your config look something like this?:

worlds: ["<world name 1>", "<world name 2>"...]

Also, make sure the names are exactly the folder names - if any are wrong, then the plugin might break.

**Comment by sanderdatema** [comment]
This is what it looks like (I didn't edit anything after).

```
# A list of worlds to form paths in
worlds: ["world_iris_s001", "world_s002"]
```

But it keeps complaining about `world` being `null`. As if it ignores the setting in the config.

**Comment by bigstickpolicies** [comment]
I've been unable to reproduce this issue - there shouldn't be anywhere where "world" is hardcoded into the plugin. Could you send me a zip of a server that's causing the issue? 

Also, where is the config file you're editing?

**Comment by sanderdatema** [comment]
I've done some more digging. I have `level-name = world_s002` in `server.properties`.
So I started with a complete clean server, Trodden Path runned fine. Then I changed the `level-name` value and immediately the errors returned. Even when the `world_s002` folder is present, Trodden Path refuses to run without error.

So... could that be a place to look?

**Comment by YKDZ** [comment]
I encountered the same problem. I also used iris generator

**Comment by bigstickpolicies** [comment]
Since I don't have access to Iris generator, I can't fully diagnose the problem. I think it might have something to do with Iris loading/unloading worlds dynamically. I can change my end to react to these changes. 

Try this version: 
[troddenpath-v1.10.jar.zip](https://github.com/bigstickpolicies/troddenpath/files/7228148/troddenpath-v1.10.jar.zip)

**Comment by sanderdatema** [comment]
Thanks for this version, v1.10 seems to work. BTW, I didn't use Iris in the test setup mentioned above. I'll attach a zip of that server: https://www.dropbox.com/s/7rmyd23ltt5gsie/minecraft.zip?dl=0

So the only steps to reproduce (on Trodden Path v1.8):
- setup new server
- run one time and copy world folder to `world_s002`
- set `level-name` in `server.properties` to `world_s002`
- run server again

Anyway, it seems to be fixed. Thanks!
